### ISSUE TITLE
Изменить скорость генерации платформ

### ISSUE THREAD

**Issue by zig1hai** [EndrII/Down#2]
Скорость игры в самом начале слишком высокая что делает её не играбельной. 
Изменить скорость генерации платформ для всех уровней сложности, предположительно уменьшить в 2 раза.

**Comment by EndrII** [comment]
Поменял скорость движения платформ (понизил 2)
[PR](https://github.com/EndrII/Down/pull/3)

**Comment by EndrII** [comment]
проект больше не поддерживается
